apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strava-statistics-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
