apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: node-red
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - nodered.travisprosser.ca
    - nodered.travisprosser.com
    - node-red.travisprosser.ca
    - node-red-new.travisprosser.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: node-red
          port: 1880
