apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-red-data
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-retain
  csi:
    driver: driver.longhorn.io
    volumeHandle: pvc-9d09ff93-a6f3-46a2-9718-f48bde3f2543  # originally dynamically created
