apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-red-data
  namespace: iot
  labels:
    app: node-red
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
