# https://github.com/kubernetes-csi/csi-driver-nfs/blob/master/charts/README.md
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
spec:
  interval: 1h
  chart:
    spec:
      chart: csi-driver-nfs
      version: 4.13.1
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
  values:
    externalSnapshotter:
      enabled: true
    controller:
      runOnControlPlane: true
      replicas: 1
    storageClass:
      create: false # use below field instead
    storageClasses:
      - name: nfs-nas
        annotations:
          storageclass.kubernetes.io/is-default-class: "false"
        parameters:
          server: 192.168.2.85
          share: /volume1/storage-travipross
          subDir: k3s-pvcs/${pvc.metadata.namespace}-ns/${pvc.metadata.name}
        reclaimPolicy: Retain
        volumeBindingMode: Immediate
        mountOptions:
          - nfsvers=4.1
          - hard
          - timeo=600
          - retrans=2
