apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-movies
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: nas-movies
    volumeAttributes:
      server: 192.168.2.85
      share: /volume1/storage-travipross/movies
