apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-movies
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
  volumeName: nas-movies
