apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-config-pv
  labels:
    app: home-assistant
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-hostpath-home-assistant
  hostPath:
    path: "/home/travipross/pvc-data/home-assistant/config"
    type: DirectoryOrCreate