apiVersion: v1
kind: PersistentVolume
metadata:
  name: esphome-config
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-retain
  csi:
    driver: driver.longhorn.io
    volumeHandle: pvc-7fac95d3-341d-4671-8d82-afdc8582634b  # originally dynamically created


