apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: default-weekly-backup
spec:
  name: default-weekly-backup
  concurrency: 1
  # Weekly Friday morning, 2:30 AM
  cron: 30 3 * * 6
  groups:
    - default
  retain: 4
  task: backup
  parameters:
    # every 4 backups, get a new full backup
    full-backup-interval: "4"
