apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system # Included in addition to kustomization.yaml due to Renovate, because name does not match that of the associated HelmRepository
spec:
  chart:
    spec:
      chart: longhorn
      version: 1.10.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
  values:
    defaultSettings:
      defaultReplicaCount: "1"
      replicaSoftAntiAffinity: true
    persistence:
      defaultClassReplicaCount: 1
    defaultBackupStore:
      backupTarget: nfs://192.168.2.85:/volume1/backup/longhorn
  interval: 1h
