apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config-pvc
  namespace: iot
  labels:
    app: frigate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual-hostpath-frigate-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media-pvc
  namespace: iot
  labels:
    app: frigate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual-hostpath-frigate-media
