apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-config-pv
  labels:
    app: frigate
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-hostpath-frigate-config
  hostPath:
    path: "/home/travipross/pvc-data/frigate/config"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-media-pv
  labels:
    app: frigate
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-hostpath-frigate-media
  hostPath:
    path: "/home/travipross/pvc-data/frigate/media"
    type: DirectoryOrCreate
