apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-nas
