apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: transmission
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      port: 8443 # common port for all 'websecure-*' listeners on gateway
  hostnames:
    - transmission.travisprosser.ca
    - transmission.travisprosser.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: transmission
          port: 9091
