apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lubelogger
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
      port: 8443 # common port for all 'websecure-*' listeners on gateway
  hostnames:
    - lubelogger.travisprosser.ca
    - lubelogger.travisprosser.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: lubelogger
          port: 8080
