apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lubelogger-protection-keys
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
