apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lubelogger-protection-keys
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeName: "pvc-79c4554e-a859-499e-bbf9-070d44110c0e" # originally dynamically created