apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-red-data-pv
  labels:
    app: node-red
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-hostpath-node-red
  hostPath:
    path: "/home/travipross/pvc-data/node-red/data"
    type: DirectoryOrCreate