apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflared
metadata:
  labels:
    app: cloudflared
resources:
  - remote-tunnel-token.enc.yaml
  - remote-tunnel-deployment.yaml
  - local-tunnel-credentials-secret.enc.yaml
  - local-tunnel-deployment.yaml
configMapGenerator:
  - name: local-tunnel-config
    files:
      - local-tunnel-config.yaml