apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:fO3LFM1x2TxPqF5AO6xUrYCUXrSfUtK+mgbic/RQGv8DH8m4PgmelVH+ejp1e9DkSGBA3ShX3uQKUPLlb3zAVMFXYy4+gjITwRzHozjhGa6dscD8tnQXz7TgSOIYe6nTDtq0yJjB1OIU3NqlE/SQpnPEs/23aH5DKGArOuzmcTW6IlWJKusjf8uUkaUTgtT8jKTclQwdQL64TnpuSmh6GBdUxKi9cKahwaCJFrRni5VYIWV+qJbkp845WVgQB2lzc13v3D0ih54dXG7QsQfZDB3SOKJyqmQITTXTeCyXYVFJqJFy/laeNBUFgbw=,iv:o9e1XtzL9kKOamYbFz+D8WU2fyE/WaSoG97o8zNYbAo=,tag:DipV3OhqaXPMna2k0dTIIg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1lyzn603kztevglyzhxxj6fcz4cptkvrt86yy7nul420w9f0kngtsnhmkln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTHo5c1ZMbWtCYmpLZUxz
            T1V0QlRLU2Q2Zkgvb3pDVWdJU21OQXhKRkJVCllHTE1Qby9GMThQSFI4Z3FDQnFR
            OEVWTCtOdXNCdU5Wa3Jzam5ESzloS2sKLS0tIFZuWVFlS3ZJSFk3d0Y5amNldGZH
            VkpMaGpGVE9NcUdmaWowYzFNc0NGSUEKazBDFpx38Y+x61Gl4W6GePhx33jsOKc3
            iNo8m+c/itmVyOMzl/oCrG7RFit73DrT+GkdoHwW5UK37okUQ4thtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T01:23:41Z"
    mac: ENC[AES256_GCM,data:F1egNQQ/amgfurSlKpxP74Q++RUZ1vA2uE5qu1b6f8BiXjgmBZ0GfIFkQL0AaOAX4py97DLKenjNF8h2ckwMzldUpzyIPdJuBpK7o7OizpIdJDPqo1pSYmhKukQ2TrWG2NZ/5fK1A5ts+K5hcarzRwKT39f4ZexWEhTm/BZ7GXk=,iv:V4TTUXDldgRsnar49n+GEhseZrCEmF6GjO3vehHFMI0=,tag:RWLWUI8D6Y4eZWA8SBDLtQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
