# https://developers.cloudflare.com/cloudflare-one/networks/connectors/cloudflare-tunnel/do-more-with-tunnels/local-management/configuration-file
tunnel: b073626e-a418-40b0-ade3-3a711b102204
credentials-file: /root/.cloudflared/credentials.json

ingress:
  - hostname: frigate.travisprosser.ca
    service: http://frigate.iot:5000 # svc.namespace
  - service: http_status:404