apiVersion: v1
stringData:
    token: ENC[AES256_GCM,data:UL9tB0gET94m65BiXx6LKbEg5WkoetJU7mpD1+oIHSbBvz/SlrqONUpvlR4TaHu/nEb63M3tp44pvTPuyOHrP4A8K1SNRA+qAoC6WE8hc5eI5YgrOBdsHD3iSigG6n3P93y3A7DXbsP+AhyKIS6pHKrRi6drtEhGnC8rs4bNnxLtfj4ln4VG/bIsMI/097Kr4LYvf3No5FEGxxTU0K1+6t5mFcPhN/7NEFHLKXiXUgHo/3wFuERDVA==,iv:j8kSyWmtMIyElDHPpL+Iu2nNzZWQf3ZJmLGUm1N+lXQ=,tag:Uui2yxVzmQhISveZkHRrEg==,type:str]
kind: Secret
metadata:
    name: tunnel-token
sops:
    age:
        - recipient: age1lyzn603kztevglyzhxxj6fcz4cptkvrt86yy7nul420w9f0kngtsnhmkln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NC83eXRiQ1dlTWVVVmZo
            dS9tdHVTRG0yK3R3OXZyNktTZStQT1M3VHdvClU0VklETnoyK0EzajNmOEk1OWV1
            d3lmZkdqZDVCZ1QvcDhlL1hKZXFRR3cKLS0tIFUxSkhyM0ExWjZpcm4zVlZmZ0lt
            eUlGS0VUNzgxNXZydlRjbGlMMTB5TGcKwAkpNrwegKwfT/zuD82EY3ykMfMEu2fy
            DnkUnj23Bdg+4GcKRjR3+bjJzj/p9BUnr0QvYEOtovftL7Xr2KVh6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T19:55:00Z"
    mac: ENC[AES256_GCM,data:9Gf++Xno/JN8A5a4V3bIK/aLKofVu5u4uFAW6hnbt6xeCdHNCGA7ctS1YsNH5/KEcdbmoEebkXhm8OJi7gRQet5rhKBKDEHdJFSGNGetT1WL0afZ2y+5036FhYrPSMb7gwPV4j1HmJ3K9FdhpcXCRcdzADHJ9KbA0izl1tdWxfk=,iv:i6GF7mM5zCFobRzd9aOqe7JrT3oM8uF+DFaygVLFzbk=,tag:h1+qEH9sCml3U7pxfvZN1g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
