apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media
  namespace: iot
  labels:
    app: frigate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
