apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
spec:
  chart:
    spec:
      chart: frigate
      version: 7.8.0
      sourceRef:
        kind: HelmRepository
        name: blakeshome
        namespace: flux-system
  interval: 1m
  # Loading chart values from file to allow for tidier organization
  valuesFrom:
    # Load helm values.yaml from generated configmap (from kustomization.yaml)
    - kind: ConfigMap
      name: frigate-chart-values
      valuesKey: "values.yaml"
