apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-code-server-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
