apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: home-assistant
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames:
    - hassio.travisprosser.ca
    - homeassistant.travisprosser.ca
    - homeassistant.travisprosser.com
    - home-assistant.travisprosser.ca
    - home-assistant.travisprosser.com
    - hassio-new.travisprosser.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: home-assistant
          port: 8123
