name: "Terraform"
on:
  push:
    branches: ["main"]
    paths:
      - "terraform/**"
      - .github/workflows/terraform.yml
  pull_request:
    paths:
      - "terraform/**"
      - .github/workflows/terraform.yml

jobs:
  terraform:
    name: "Plan / Apply Terraform"
    runs-on: ubuntu-latest
    environment: home-server

    defaults:
      run:
        shell: bash
        working-directory: terraform

    permissions:
      pull-requests: write

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_ENDPOINT_URL_S3: ${{ secrets.AWS_ENDPOINT_URL_S3 }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      TF_VAR_travisprosser_ca_zone_id: ${{ secrets.TF_VAR_zone_id }}
      TF_VAR_cf_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      TF_VAR_google_oauth_client_id: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
      TF_VAR_google_oauth_client_secret: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v6
      - uses: hashicorp/setup-terraform@v4

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -no-color
        continue-on-error: true

      - name: Create PR Comment
        uses: actions/github-script@v8
        env:
          PLAN: "${{ steps.plan.outputs.stdout }}"
          PLAN_ERROR: "${{ steps.plan.outputs.stderr }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `\n#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`\n
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`\n
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`\n
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`

            </details>

            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            ${process.env.PLAN_ERROR}

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>`;


            // Add output to summary
            await core.summary
              .addHeading('Terraform Results')
              .addRaw(output)
              .write()

            // If this is a PR, try to create/update a comment
            if (context.issue.number) {
              const { data: comments } = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
              })

              const botComment = comments.find(comment => {
                return comment.user.type === 'Bot' && comment.body.includes('Terraform Format and Style')
              })

              // If we have a comment, update it, otherwise create a new one
              if (botComment) {
                github.rest.issues.updateComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: botComment.id,
                  body: output
                })
              } else {
                github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: output
                })
              }
            }

      - name: Exit if any previous step with 'continue-on-error' failed
        if: steps.plan.outcome == 'failure' || steps.fmt.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          # disable errexit temporarily so the step doesn't fail immediately if the following command fails 
          set +e
          terraform apply -auto-approve -input=false -no-color > apply_results.txt 2>&1
          APPLY_EXIT_CODE=$?
          set -e

          if [ $APPLY_EXIT_CODE -eq 0 ]; then
            echo "#### Terraform Apply ✅ (Success)" >> $GITHUB_STEP_SUMMARY
          else
            echo "#### Terraform Apply ❌ (Failed)" >> $GITHUB_STEP_SUMMARY
          fi

          echo "<details><summary>Show Detailed Logs</summary>" >> $GITHUB_STEP_SUMMARY
          
          # add a newline to preserve formatting in details block
          echo "" >> $GITHUB_STEP_SUMMARY

          # wrap results in terraform-formatted code block
          echo '```terraform' >> $GITHUB_STEP_SUMMARY
          cat apply_results.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

          # close 
          echo "</details>" >> $GITHUB_STEP_SUMMARY

          # exit with captured exit code
          exit $APPLY_EXIT_CODE
