apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zwave-js-ui-config
  labels:
    app: zwave-js-ui
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
