apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-data-pv
  labels:
    app: mosquitto
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-hostpath-mosquitto
  hostPath:
    path: "/home/travipross/pvc-data/mosquitto/data"
    type: DirectoryOrCreate